// Generated by FlutterFire CLI — do not edit manually.
// Run `flutterfire configure` to regenerate after adding new platforms.

import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show TargetPlatform, defaultTargetPlatform, kIsWeb;

class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) throw UnsupportedError('Web platform is not supported.');
    return switch (defaultTargetPlatform) {
      TargetPlatform.android => android,
      TargetPlatform.iOS => ios,
      _ => throw UnsupportedError(
          'Platform $defaultTargetPlatform is not supported.',
        ),
    };
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCG3_vDvddiW3nNPZ2f-3tVrhylIOB1TZs',
    appId: '1:531670640472:android:95d1327b19fa076effe72d',
    messagingSenderId: '531670640472',
    projectId: 'mine-fca38',
    databaseURL: 'https://mine-fca38-default-rtdb.firebaseio.com',
    storageBucket: 'mine-fca38.firebasestorage.app',
  );
  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyASQAibBWlHWARGJ0tIhd8fzXLoRDa0Bk0',
    appId: '1:531670640472:ios:ed7e63895959f0b4ffe72d',
    messagingSenderId: '531670640472',
    projectId: 'mine-fca38',
    databaseURL: 'https://mine-fca38-default-rtdb.firebaseio.com',
    storageBucket: 'mine-fca38.firebasestorage.app',
    iosClientId: '531670640472-em7csqpeockvrrftnlimsutnt7b9blht.apps.googleusercontent.com',
    iosBundleId: 'com.rathtech.securechat',
  );
}
